// automatically generated by archetype.js

this.option = {

  database: {
    database: '%PROJECT%',
    username: '',
    password: '',
    options: {
      host: 'localhost',
      port: 3306,
      disableLogging: false,
      disableTableNameModification: true,
      fetchAssociations: false,
      refetchAssociations: false
    }
  },

  debug: true,

  fs: {
    mode: 0755
  },

  http: {
    host: '127.0.0.1',
    port: 8192
  },

  log: {
    truncate: false,
    logs: [archetype_project_root+'/%PROJECT%.log']
  }

};
