// automatically generated by archetype.js

this.option = {

  cache: {
    lifetime: 5000,
    servers: [
      '127.0.0.1:11211'
    ],
  },

  debug: true,

  fs: {
    mode: 0755
  },

  http: {
    host: '127.0.0.1',
    port: 8192
  },

  log: {
    truncate: false,
    logs: [archetype_project_root+'/%PROJECT%.log']
  },

  repl: {
    host: '127.0.0.1',
    port: 8193
  }

};
