// automatically generated by archetype.js

var models = {

  %MODULE%: {
    title: {
      type: STRING,
      allowNull: false,
      default: ''
    },
    description: {
      type: TEXT,
      allowNull: true
    }
  }

};
