// automatically generated by archetype.js

var routes = {

  %MODULE%_route: {
    title: 'Index for %MODULE% module',
    mime: 'text/plain',
    pattern: '^/%MODULE%(.*)$',
    service: '%MODULE%',
    callback: 'index'
  }

};
