// automatically generated by archetype.js

var routes = {

  %MODULE%_route: {
    title: 'Index for %MODULE% module',
    mime: 'text/html',
    pattern: '^/%MODULE%(.*)$',
    service: '%MODULE%',
    callback: 'index',
    template: '%MODULE%_index'
  }

};
