// automatically generated by archetype.js

var models = require('archetype/database').database.models;

this.index = function (request, response) {
  models.%MODULE%.sync();
  response.writeHead(200, {'Content-Type': request.__route.mime});
  return {title: request.__route.title, path: request.url};
};
